#git aliases
alias g='git'
alias gs='git st'
alias ga='git add'
alias gco='git co'
alias gp='git put'
alias gci='git ci'
alias gup='git up'
alias gd='git diff'
alias gdc='git diffc'
alias gm='git merge'
alias gg='git grep'
alias gb='git br'
alias glg='git lg'
